-- https://www.hackerrank.com/challenges/weather-observation-station-5/problem

SELECT MIN(CITY), LEN
FROM (SELECT CITY, LENGTH(CITY) AS LEN FROM STATION) AS SUB
GROUP BY LEN
HAVING
    LEN IN 
        ((SELECT MAX(LENGTH(CITY)) FROM STATION),
        (SELECT MIN(LENGTH(CITY)) FROM STATION));
        
-- OR

(SELECT CITY, LENGTH(CITY)
FROM STATION
WHERE LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION)
ORDER BY CITY
LIMIT 1)
UNION
(SELECT CITY, LENGTH(CITY)
FROM STATION
WHERE LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) FROM STATION)
ORDER BY CITY
LIMIT 1);
